name: jekyll_app
type: ruby:2.3
disk: 1024
web:
  locations:
    "/":
      root: "_site"
      index:
        - index.html
      passthru: false
hooks:
  build: |
    gem install bundler -v '~> 2.1.4'
    bundle install --binstubs
    find . -type f -iname 'jekyll'
    bin/jekyll build
